/*
 * Cloud Payment API
 * Eximbay Cloud Payment API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.eximbay.demolibrary.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.eximbay.demolibrary.model.RefundResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * RefundAllResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-10T05:33:55.380Z[GMT]")
public class RefundAllResponse {
  @SerializedName("remaining")
  private Boolean remaining = null;

  @SerializedName("data")
  private List<RefundResponse> data = null;

  public RefundAllResponse remaining(Boolean remaining) {
    this.remaining = remaining;
    return this;
  }

   /**
   * Get remaining
   * @return remaining
  **/
  @Schema(description = "")
  public Boolean isRemaining() {
    return remaining;
  }

  public void setRemaining(Boolean remaining) {
    this.remaining = remaining;
  }

  public RefundAllResponse data(List<RefundResponse> data) {
    this.data = data;
    return this;
  }

  public RefundAllResponse addDataItem(RefundResponse dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<RefundResponse>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public List<RefundResponse> getData() {
    return data;
  }

  public void setData(List<RefundResponse> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundAllResponse refundAllResponse = (RefundAllResponse) o;
    return Objects.equals(this.remaining, refundAllResponse.remaining) &&
        Objects.equals(this.data, refundAllResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(remaining, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundAllResponse {\n");
    
    sb.append("    remaining: ").append(toIndentedString(remaining)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
